# Use postgres/example user/password credentials

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
      PORT: 8110
    ports:
      - "8110:8110"
